name: Publish release_name
on:
  workflow_dispatch:

jobs:
  publish-release:
    name: Publish release_name
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 20.8.1
        uses: actions/setup-node@v3
        with:
          node-version: "20.8.1"

      - name: Create release
        run: npx semantic-release
